import {anatomyLabel,medicalLabel} from '../lib/medical-language';
import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {advanced,artifactUrl,number,workflows,type Job} from '../lib/advanced';

const names:Record<string,string>={sliceIndex:'L3 metszet száma (az első: 0)',method:'Módszer',selectedMuscleAreaCm2:'Kijelölt izmok (cm²)',selectedMuscleMeanHu:'Kijelölt izmok átlagos HU',fatRangeAreaCm2:'Zsírtartomány (cm²)',totalMuscleAreaCm2:'Teljes izomterület (cm²)',skeletalMuscleIndexCm2M2:'Vázizomindex (cm²/m²)',visceralFatAreaCm2:'Visceralis zsír (cm²)',subcutaneousFatAreaCm2:'Subcutan zsír (cm²)',muscleMeanHu:'Izom átlagos HU',intermuscularFatAreaCm2:'Intermuscularis zsír (cm²)'};
export default function AdvancedReportPage(){
 const {jobId}=useParams();const [job,setJob]=useState<Job|null>(null),[error,setError]=useState('');
 useEffect(()=>{void advanced<Job>(`/jobs/${jobId}`).then(setJob).catch(e=>setError(e.message));},[jobId]);
 if(error)return <p role="alert">{error}</p>;if(!job?.report)return <p>Jelentés betöltése…</p>;
 const r=job.report,review=job.review;
 const table=(headers:string[],rows:(string|number|null|undefined)[][])=><div className="advanced-table-scroll"><table className="advanced-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==='number'?number(v,6):v??'—'}</td>)}</tr>)}</tbody></table></div>;
 return <article className="advanced-report care-panel"><div className="advanced-actions no-print"><Link to={`/advanced?module=${job.kind}&job=${job.id}`} className="button secondary">Vissza a munkatérhez</Link><button className="button primary" onClick={()=>window.print()}>Mentés PDF-ként / nyomtatás</button><span>A nyomtatási ablakban válaszd a „Mentés PDF-ként” lehetőséget.</span></div><p className="advanced-step">LELETÍV · KUTATÁSI MÉRÉSI JELENTÉS</p><h1>{workflows.find(w=>w.id===job.kind)?.title}</h1><p>{String(job.options?.title??'')} · {new Date(job.created*1000).toLocaleString('hu-HU')}</p><p><strong>{review?'Ellenőrzött kutatási eredmény':'Nem ellenőrzött automatikus eredmény'}</strong> · Nem klinikai lelet.</p><p>Esetazonosító: {String(job.options?.caseId||'Önálló vizsgálat')} · Futás: {job.id}</p>{job.options?.synthetic===true&&<p>Szintetikus geometriai próba, nem betegvizsgálat.</p>}
 {job.kind==='longitudinal'&&<>{r.visits!.map((v,i)=><section key={i}><h2>{i+1}. kontroll</h2>{table(['Kiinduló régió','Kontrollrégió','Kiinduló ml','Kontroll ml','Változás %'],r.baseline!.map(b=>{const match=(review?.matching?.[i]??v.matching).find(p=>p.baselineLabel===b.label);const f=v.regions.find(f=>f.label===match?.followupLabel);return [b.label,f?.label??'Nem azonosítható',b.volumeMl,f?.volumeMl,f&&b.volumeMl?(f.volumeMl/b.volumeMl-1)*100:null];}))}</section>)}{review?.recist&&<><h2>RECIST 1.1 munkalap</h2>{table(['Kontroll','Átmérőösszeg (mm)','Változás %','Korábbi legkisebb átmérőösszeg (mm)','Összesített kategória'],review.recist.visits.map(v=>[v.visit,v.sumMm,v.baselineChangePercent,v.nadirBeforeMm,v.overallResponse]))}<p>{review.recist.limitations}</p></>}</>}
 {job.kind==='body'&&<><h2>Testösszetétel az L3 szintjében</h2>{r.composition?table(['Mérés','Érték'],Object.entries(r.composition).map(([k,v])=>[names[k]??k,typeof v==='string'?medicalLabel(v):v])):<p>L3-mérés nem készült.</p>}<h2>Anatómiai térfogatok</h2>{table(['Régió','Térfogat (ml)'],r.regions!.map(x=>[anatomyLabel(x.name),x.volumeMl]))}</>}
 {job.kind==='pet'&&<><h2>PET aktivitásrégiók</h2>{table(['Régió','Beszámítva','Térfogat ml','SUVmean','SUVmax','TLG'],r.regions!.map(x=>[x.label,review?.includedRegions?.includes(x.label)?'Igen':'Nem',x.volumeMl,x.suvMean,x.suvMax,x.tlg]))}{review&&<p>Kiválasztott metabolikus térfogat: {number(review.metabolicVolumeMl)} ml · TLG: {number(review.tlg)}.</p>}</>}
 {job.kind==='pathology'&&<><h2>Sejtmag-pozitivitás a kijelölt régióban</h2><p>Automatikusan felismert sejtmagok: {r.summary!.cells}. {review?`Ellenőrzött pozitív arány: ${number(review.positivePercent)}%.`:`Automatikus pozitív arány: ${number(r.summary!.positivePercent)}%.`}</p>{review?.counts&&table(['Besorolás','Sejtmag'],[['Pozitív',review.counts.positive],['Negatív',review.counts.negative],['Kizárt',review.counts.excluded]])}<p>Vizsgált terület: x={r.roi!.x}, y={r.roi!.y}, {r.roi!.width} × {r.roi!.height} képpont. A teljes sejtenkénti lista és a javítások a JSON-csomagban találhatók.</p><img className="advanced-report-slide" src={artifactUrl(job,'cells.png')} alt="Automatikus sejtmagjelölések a vizsgált régióban"/><p>A képen az eredeti automatikus jelölések láthatók; a javított besorolást a mentett összesítés tartalmazza.</p></>}
 {job.kind==='mri'&&<><h2>Régiónkénti mérések</h2>{table(['Térkép','Régió','Méréshez használt képpontok','Medián','P10','P90'],r.measurements!.map(m=>[m.map,m.region,m.validVoxels,m.median,m.p10,m.p90]))}<p>ADC: mm²/s. rCBV: normál referenciaszövetre normalizált relatív érték. DSC: szivárgáskorrekció nélküli ΔR2*-integrál.</p></>}
 <h2>Ellenőrzés</h2><p>{review?`${review.reviewer} · ${new Date(review.time*1000).toLocaleString('hu-HU')} · ${job.version}. változat`:'Még nincs rögzített ellenőrzés.'}</p><p>{review?.note}</p><h2>Módszer és korlátok</h2><p>{medicalLabel(r.method)}</p><ul>{r.limitations.map(l=><li key={l}>{medicalLabel(l)}</li>)}</ul><p>Feldolgozási idő: {number(r.elapsedSeconds)} másodperc. A verziózott ellenőrzések, paraméterek és SHA-256 azonosítók a teljes JSON-eredménycsomagban szerepelnek.</p></article>;
}
