import {medicalLabel} from '../lib/medical-language';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Brain,Scan,TrendUp,Microscope,Stack} from '@phosphor-icons/react';
import {PageHeader} from '../components/ui';
import {AdvancedInputs} from '../components/AdvancedInputs';
import {AdvancedViewer} from '../components/AdvancedViewer';
import {AdvancedReview} from '../components/AdvancedReview';
import {advanced,workflows,statusLabel,type Workflow,type Job,type Capabilities} from '../lib/advanced';

const icons=[TrendUp,Stack,Scan,Microscope,Brain];
export default function AdvancedPage(){
 const [query,setQuery]=useSearchParams();const selected=query.get('module');const kind:Workflow=workflows.find(w=>w.id===selected)?.id??'longitudinal';
 const [cap,setCap]=useState<Capabilities|null>(null),[jobs,setJobs]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connection,setConnection]=useState('Kapcsolódás a helyi feldolgozóhoz…'),[focus,setFocus]=useState<number[]|undefined>();
 const current=useRef<string|null>(null),resultRef=useRef<HTMLDivElement>(null);
 const refresh=useCallback(async()=>{try{const [c,j]=await Promise.all([advanced<Capabilities>('/capabilities'),advanced<Job[]>('/jobs')]);setCap(c);setJobs(j);setConnection('Helyi feldolgozó elérhető');}catch{setCap(null);setConnection('A helyi feldolgozó nem érhető el.');}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{const id=query.get('job');current.current=id;if(!id){setJob(null);return;}setError('');let live=true;const read=async()=>{try{const next=await advanced<Job>(`/jobs/${id}`);if(live&&current.current===id)setJob(previous=>previous?.version===next.version&&previous.status===next.status&&previous.progress===next.progress?previous:next);}catch(e){if(live)setError((e as Error).message);}};void read();const timer=setInterval(()=>void read(),2500);return()=>{live=false;clearInterval(timer);};},[query.get('job')]);
 const contextCase=query.get('case');const contextQuery:Record<string,string>=contextCase?{case:contextCase}:{};
 const choose=(id:Workflow)=>{setQuery({...contextQuery,module:id});setJob(null);setFocus(undefined);setError('');};
 const start=async(form?:FormData,model=false)=>{setBusy(true);setError('');try{const created=await advanced<Job>(form?`/jobs/${kind}`:`/demo/${kind}${model?'?model=true':''}`,{method:'POST',body:form??JSON.stringify({caseId:contextCase?.startsWith('demo-leletiv-')?contextCase:undefined})});setJob(created);setQuery({...contextQuery,module:kind,job:created.id});void refresh();setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),100);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const active=job&&['queued','running'].includes(job.status);
 return <div className="advanced-workspace"><PageHeader eyebrow="LELETÍV · KVANTITATÍV MUNKATÉR" title="A képtől a mérésig." description="Öt helyben futó munkafolyamat. Követhető feldolgozás, ellenőrizhető eredmények, közös dokumentálás." actions={<Link className="button secondary" to="/volume-lab">3D képi munkatér ↗</Link>}/>
 <div className="advanced-status"><span className={`advanced-dot ${cap?'is-ready':''}`}/><strong>{connection}</strong><span>Külső szolgáltatás és API-kulcs nélkül</span><button className="text-button" onClick={()=>void refresh()}>Kapcsolat ellenőrzése</button></div>
 {!cap&&<aside className="care-panel"><h2>Indítsd el a helyi elemzőt</h2><p>A képfeldolgozás a gépeden futó Python-szolgáltatást használja. A projekt mappájában: <code>npm run dev:full</code>. Első telepítés: <code>npm run advanced:setup</code>, majd <code>npm run advanced:body-model</code>.</p></aside>}
 <nav className="advanced-module-grid" aria-label="Kvantitatív munkafolyamatok">{workflows.map((w,i)=>{const Icon=icons[i];return <button key={w.id} className={w.id===kind?'is-active':''} aria-pressed={w.id===kind} onClick={()=>choose(w.id)}><Icon size={27} weight="duotone"/><span className="advanced-module-number">0{i+1}</span><strong>{w.title}</strong><small>{w.short}</small></button>;})}</nav>
 <div className="advanced-intro"><h2>{workflows.find(w=>w.id===kind)!.short}</h2><p>{workflows.find(w=>w.id===kind)!.description}</p></div>
 {cap&&kind==='body'&&<p className="advanced-hint">Szervmodell: {cap.bodyWeights?'telepítve':'nincs telepítve'} · Testösszetételi modell: {cap.compositionWeights?'telepítve':'nincs telepítve'}. A minta ismert területkijelölésekkel ellenőrzi a méréseket. <button className="text-button" disabled={busy||!cap.bodyWeights} onClick={()=>void start(undefined,true)}>Valódi modellek futtatása szintetikus CT-n</button></p>}
 <AdvancedInputs key={kind+query.get('case')} kind={kind} busy={busy||!cap} onStart={f=>void start(f)} onDemo={()=>void start()}/>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 <div ref={resultRef} className="advanced-current" aria-live="polite">{job&&<section className="care-panel advanced-job"><div><span className="advanced-step">Feldolgozás · {job.id.slice(0,8)}</span><h2>{String(job.options?.title||workflows.find(w=>w.id===job.kind)?.title)}</h2><p>{job.stage}</p></div><div><span className="advanced-pill">{statusLabel[job.status]??job.status}</span>{active&&<button className="button secondary" onClick={()=>{void advanced(`/jobs/${job.id}/cancel`,{method:'POST',body:'{}'}).catch(e=>setError(e.message));}}>Feldolgozás megszakítása</button>}</div>{active&&<progress aria-label="Feldolgozás állapota" max={100} value={job.progress}/ >}{job.error&&<p role="alert">{medicalLabel(job.error)}</p>}{job.options?.synthetic===true&&<p className="advanced-hint">Szintetikus geometriai próba. Műszaki ellenőrzésre szolgál; a klinikai pontosságot nem igazolja.</p>}</section>}</div>
 {job?.status==='completed'&&job.report&&<><AdvancedViewer key={job.id} job={job} focus={focus}/><AdvancedReview key={job.id} job={job} onSaved={j=>{setJob(j);void refresh();}} onFocus={p=>{setFocus([...p]);document.querySelector('.advanced-viewer')?.scrollIntoView({behavior:'smooth',block:'center'});}}/></>}
 <section className="care-panel advanced-history"><div className="advanced-section-title"><div><span className="advanced-step">Korábbi munka</span><h2>Mentett feldolgozások</h2></div><span>{jobs.filter(j=>j.kind===kind&&(!contextCase||j.caseId===contextCase)).length} feldolgozás ebben a modulban</span></div>{!jobs.some(j=>j.kind===kind&&(!contextCase||j.caseId===contextCase))&&<p>Itt jelennek meg a feldolgozások és a mentett ellenőrzések. Első lépésként próbáld ki a szintetikus mintát.</p>}<div className="advanced-history-list">{jobs.filter(j=>j.kind===kind&&(!contextCase||j.caseId===contextCase)).map(j=><button key={j.id} className={job?.id===j.id?'is-active':''} onClick={()=>{setQuery({...contextQuery,module:j.kind,job:j.id});setFocus(undefined);resultRef.current?.scrollIntoView({behavior:'smooth'});}}><span>{j.title&&<strong>{j.title}</strong>}<strong>{new Date(j.created*1000).toLocaleString('hu-HU')}</strong><small>{j.id.slice(0,8)} · {j.version?`${j.version} mentett ellenőrzés`:'Még nincs ellenőrzés'}</small></span><span className="advanced-pill">{statusLabel[j.status]}</span><span>Megnyitás ↗</span></button>)}</div></section>
 </div>;
}
