import {recordText} from '../lib/i18n';
import {useEffect,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useAppData} from '../lib/workspace';
import {apiRequest} from '../lib/api';
import {PageHeader,StatusBadge} from '../components/ui';
import {examLabels,examTransitions,type DecisionStep,type ExpectedExam,type ScanAnalysis} from '../shared/care';
type Care={steps:DecisionStep[];exams:ExpectedExam[];analyses:ScanAnalysis[];events:{id:string;exam_id:string;status:string;note:string;occurred_at:string}[];documents:{id:string;title:string}[]};
export default function CarePage(){
 const {data,reload,setTaskStatus}=useAppData();const [params,setParams]=useSearchParams();
 const caseId=params.get('case')||data?.cases[0]?.id||'';
 const [care,setCare]=useState<Care|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[decision,setDecision]=useState('');
 const decisions=data?.decisions.filter(d=>d.case_id===caseId)||[];const selected=decisions.find(d=>d.id===decision)||decisions[0];
 const load=async()=>setCare(await apiRequest<Care>(`/api/care/cases/${caseId}`));
 useEffect(()=>{let active=true;setCare(null);setError('');if(caseId)void apiRequest<Care>(`/api/care/cases/${caseId}`).then(v=>{if(active)setCare(v);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[caseId]);
 const run=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await fn();await load();await reload();}catch(e){setError(e instanceof Error?e.message:'A mentés nem sikerült.');}finally{setBusy(false);}};
 const send=(path:string,body:unknown,method='POST')=>apiRequest(path,{method,body:JSON.stringify(body)});
 const form=(e:FormEvent<HTMLFormElement>,fn:(b:Record<string,FormDataEntryValue>)=>Promise<unknown>)=>{e.preventDefault();const el=e.currentTarget;const body=Object.fromEntries(new FormData(el));void run(async()=>{await fn(body);el.reset();});};
 const owners=(name='owner_id')=><label>{name==='owner_id'?'Felelős':'Ellenőrző / rögzítő'}<select required name={name}><option value="">Válassz munkatársat</option>{data?.team.map(t=><option key={t.id} value={t.id}>{recordText(t.name)}</option>)}</select></label>;
 return <><PageHeader title="Döntéstől az eredményig" description="Jóváhagyott végrehajtási lépések, várt vizsgálatok és ellenőrzött eredmények." actions={<Link className="button secondary" to={`/cases/${caseId}`}>Betegút megnyitása</Link>}/>
 <label className="care-picker">Eset<select value={caseId} disabled={busy} onChange={e=>setParams({case:e.target.value})}>{data?.cases.map(c=><option key={c.id} value={c.id}>{c.patient_name} · {c.hospital_id}</option>)}</select></label>
 {error&&<p className="error-banner" role="alert">{error}</p>}{!care&&!error&&<p role="status">Betöltés…</p>}
 {care&&<fieldset disabled={busy} className="care-workspace"><section className="care-panel"><h2>Onkoteam végrehajtási terv</h2><p>A rögzített lépések a Feladatkoordinációban is megjelennek. A „Kész” feladat külön eredményellenőrzés után számít teljesített tervlépésnek.</p>
 {selected?<><label>Döntés<select value={selected.id} onChange={e=>setDecision(e.target.value)}>{decisions.map(d=><option key={d.id} value={d.id}>{recordText(d.recommendation)}</option>)}</select></label><p className="care-source">{recordText(selected.recommendation)}</p>
 <strong>{care.steps.filter(s=>s.decision_id===selected.id&&s.reviewed_at).length} / {care.steps.filter(s=>s.decision_id===selected.id).length} lépés ellenőrizve</strong>
 {care.steps.filter(s=>s.decision_id===selected.id).map(s=><article className="care-row" key={s.id}><h3>{recordText(s.title)}</h3><p>{recordText(s.owner_name)} · {s.due_at.slice(0,10)} · <StatusBadge status={s.status}/></p><p>Elvárt eredmény: {s.expected_result}</p>{s.prerequisite_id&&<p>Előfeltétel: {care.steps.find(p=>p.id===s.prerequisite_id)?.title}</p>}
 {s.reviewed_at?<p className="care-success">Ellenőrizve: {s.result_note} · {s.reviewed_at.slice(0,10)}</p>:<><label>Feladat állapota<select value={s.status} onChange={e=>void run(()=>setTaskStatus(s.task_id,e.target.value as 'done'))}><option value="open">Nyitott</option><option value="in-progress">Folyamatban</option><option value="blocked">Elakadt</option><option value="done">Kész</option></select></label><details><summary>Eredmény ellenőrzése</summary><form className="care-form" onSubmit={e=>form(e,b=>send(`/api/care/steps/${s.id}/review`,b))}>{owners('actor_id')}<label>Eredmény és forráshivatkozás<textarea name="note" required maxLength={1000}/></label><button className="button secondary" disabled={s.status!=='done'||!!(s.prerequisite_id&&!care.steps.find(p=>p.id===s.prerequisite_id)?.reviewed_at)}>Ellenőrzés rögzítése</button></form></details></>}</article>)}
 <details><summary>Új végrehajtási lépés</summary><form className="care-form" onSubmit={e=>form(e,b=>send(`/api/care/decisions/${selected.id}/steps`,b))}><label>Teendő<input name="title" required maxLength={160}/></label>{owners()}<label>Határidő<input name="due_date" type="date" required/></label><label>Előfeltétel<select name="prerequisite_id"><option value="">Nincs</option>{care.steps.filter(s=>s.decision_id===selected.id).map(s=><option value={s.id} key={s.id}>{recordText(s.title)}</option>)}</select></label><label>Elvárt eredmény<textarea name="expected_result" required maxLength={1000}/></label><button className="button primary">Lépés jóváhagyása és feladat létrehozása</button></form></details></>:<p>Még nincs rögzített onkoteam-döntés. <Link to="/board">Onkoteam megnyitása →</Link></p>}</section>
 <section className="care-panel"><h2>Várt vizsgálatok és leletek</h2><p>A vizsgálat megtörténte, az eredmény beérkezése és az orvosi áttekintés külön lépés.</p>
 <details><summary>Új várt vizsgálat</summary><form className="care-form" onSubmit={e=>form(e,b=>send(`/api/care/cases/${caseId}/exams`,b))}><label>Vizsgálat / várt eredmény<input name="title" required maxLength={160}/></label>{owners()}<label>Lelet várható beérkezése<input type="date" name="due_date" required/></label><button className="button primary">Nyilvántartásba vétel</button></form></details>
 {!care.exams.length&&<p>Nincs nyilvántartott várt vizsgálat.</p>}{care.exams.map(ex=><article className="care-row" key={ex.id}><h3>{ex.title}</h3><p>{recordText(ex.owner_name)} · {examLabels[ex.status]} · Lelet várható: {ex.due_date}</p>{ex.due_date<new Date().toLocaleDateString('sv-SE')&&!['received','reviewed','cancelled'].includes(ex.status)&&<strong className="care-overdue">Lejárt leletvárási határidő</strong>}{ex.appointment_date&&<p>Vizsgálati időpont: {ex.appointment_date}</p>}<p>{ex.note}</p>
 {examTransitions[ex.status]?.length>0&&<ExamUpdate key={ex.version} exam={ex} studies={data?.studies.filter(s=>s.case_id===caseId)||[]} documents={care.documents} owners={owners('actor_id')} submit={b=>run(()=>send(`/api/care/exams/${ex.id}`,{...b,version:ex.version},'PATCH'))}/>}
 {ex.study_id&&<Link to={`/volume-lab?study=${ex.study_id}`}>Kapcsolt képanyag →</Link>}{ex.document_id&&<Link to={`/review?case=${caseId}`}>Kapcsolt lelet →</Link>}
 <details><summary>Állapottörténet</summary>{care.events.filter(v=>v.exam_id===ex.id).map(v=><p key={v.id}>{v.occurred_at.slice(0,16)} · {examLabels[v.status]} · {v.note}</p>)}</details></article>)}</section>
 <section className="care-panel"><h2>Képértékelési napló</h2><p>Az archív képanyaghoz kötött, visszanyitható mérések és maszkok.</p>{care.analyses.length?care.analyses.map(a=><article className="care-row" key={a.id}><h3>{a.region_id}</h3><p>{a.method} · {a.review_status==='reviewed'?'Áttekintve':'Ellenőrzésre vár'} · {a.created_at.slice(0,10)}</p><p>{a.note}</p><Link to={`/volume-lab?study=${a.study_id}&analysis=${a.id}`}>Forrás és mentett maszk megnyitása →</Link></article>):<p>Még nincs mentett képértékelés.</p>}</section></fieldset>}</>;
}
function ExamUpdate({exam,studies,documents,owners,submit}:{exam:ExpectedExam;studies:{id:string;description:string}[];documents:{id:string;title:string}[];owners:React.ReactNode;submit:(b:Record<string,FormDataEntryValue>)=>Promise<void>}){
 const [next,setNext]=useState(examTransitions[exam.status][0]);return <details><summary>Következő lépés rögzítése</summary><form className="care-form" onSubmit={e=>{e.preventDefault();void submit(Object.fromEntries(new FormData(e.currentTarget)));}}><label>Új állapot<select name="status" value={next} onChange={e=>setNext(e.target.value)}>{examTransitions[exam.status].map(s=><option key={s} value={s}>{examLabels[s]}</option>)}</select></label>{owners}{next==='scheduled'&&<label>Vizsgálat időpontja<input name="appointment_date" type="date" required/></label>}{next==='received'&&<><label>Beérkezett képanyag<select name="study_id"><option value="">Nincs</option>{studies.map(s=><option key={s.id} value={s.id}>{s.description}</option>)}</select></label><label>Beérkezett lelet<select name="document_id"><option value="">Nincs</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label></>}<label>Megjegyzés / értékelés és következő teendő<textarea name="note" required maxLength={1000}/></label><button className="button primary">Állapot mentése</button></form></details>;
}
