import {translate} from '../lib/i18n';
import {useEffect,useRef,useState} from 'react';
import {Niivue,NVImage} from '@niivue/niivue';
import {useAppData} from '../lib/workspace';
import {demoCases} from '../shared/demo';
import {Link,useSearchParams} from 'react-router-dom';
import {PageHeader} from '../components/ui';
import {assertSameGrid,measureLabels} from '../shared/volume';
import {decodeVolume,hashBytes,maskFile} from '../shared/nifti-data';
import {maskDifference} from '../shared/region-tools';
import {downloadText} from '../lib/download';
type Scan=Awaited<ReturnType<typeof decodeVolume>> & {hash:string;name:string};
export default function ComparePage(){
 const [params]=useSearchParams();const demoCase=params.get('case');const {data}=useAppData();const [viewerReady,setViewerReady]=useState(false);const opened=useRef('');
 const left=useRef<HTMLCanvasElement>(null),right=useRef<HTMLCanvasElement>(null),viewers=useRef<Niivue[]>([]);
 const [sources,setSources]=useState<(Scan|null)[]>([null,null]),[masks,setMasks]=useState<(Scan|null)[]>([null,null]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[sync,setSync]=useState(false),[dates,setDates]=useState(['','']);
 useEffect(()=>{let live=true;const list=[left,right].map(()=>new Niivue({backColor:[.97,.98,1,1],dragAndDropEnabled:false,isColorbar:false,logLevel:'error'}));viewers.current=list;void Promise.all(list.map((nv,i)=>nv.attachToCanvas([left,right][i].current!))).then(()=>{if(live){list.forEach(nv=>nv.setSliceType(nv.sliceTypeMultiplanar));setViewerReady(true);}}).catch(()=>{if(live)setError('A 3D megjelenítés nem indítható.');});return()=>{live=false;list.forEach(nv=>nv.cleanup());viewers.current=[];};},[]);
 const load=async(file:File,i:number,mask:boolean)=>{setBusy(true);setDifferenceShown(false);setError('');setConfirmed(false);setSync(false);viewers.current.forEach(nv=>nv.broadcastTo([]));try{const d=await decodeVolume(file),scan={...d,hash:await hashBytes(d.bytes),name:file.name};if(mask){if(!sources[i])throw new Error('Előbb nyisd meg a forrásképet.');assertSameGrid(sources[i]!.geometry,d.geometry);measureLabels(d.data,d.geometry);}const nv=viewers.current[i];const image=await NVImage.loadFromFile({file:d.safe,colormap:mask?'red':'gray',opacity:mask?.7:1});if(mask){while(nv.volumes.length>1)nv.removeVolumeByIndex(1);}else{while(nv.volumes.length)nv.removeVolumeByIndex(0);}nv.addVolume(image);if(mask)setMasks(p=>p.map((v,j)=>i===j?scan:v));else{setSources(p=>p.map((v,j)=>i===j?scan:v));setMasks(p=>p.map((v,j)=>i===j?null:v));}}catch(e){setError(translate((e as Error).message));}finally{setBusy(false);}};
 const [differenceShown,setDifferenceShown]=useState(false);
 const demo=async()=>{setBusy(true);setError('');setConfirmed(false);setSync(false);setDifferenceShown(false);viewers.current.forEach(nv=>nv.broadcastTo([]));try{const scans=await Promise.all(['baseline','followup','baseline-mask','followup-mask'].map(async name=>{const linked=demoCases.some(p=>p.id===demoCase);const visit=name.startsWith('followup')?1:0;const endpoint=linked?(name.endsWith('-mask')?`/api/scans/analyses/${demoCase}-study-${visit}-analysis/mask`:`/api/studies/${demoCase}-study-${visit}/download`):'/imaging-demo/'+name+'.nii.gz';const r=await fetch(endpoint);if(!r.ok)throw new Error('A szintetikus példa nem érhető el.');const d=await decodeVolume(new File([await r.blob()],name+'.nii.gz'));return {...d,hash:await hashBytes(d.bytes),name:({'baseline':'Próbakép · kiinduló vizsgálat','followup':'Próbakép · kontrollvizsgálat','baseline-mask':'Kiinduló területkijelölés','followup-mask':'Kontroll területkijelölése'} as Record<string,string>)[name]};}));for(let i=0;i<2;i++){const nv=viewers.current[i];while(nv.volumes.length)nv.removeVolumeByIndex(0);nv.addVolume(await NVImage.loadFromFile({file:scans[i].safe,colormap:'gray'}));nv.addVolume(await NVImage.loadFromFile({file:scans[i+2].safe,colormap:'red',opacity:.7}));}setSources(scans.slice(0,2));setMasks(scans.slice(2));setDates([0,1].map(v=>data?.studies.find(s=>s.id===`${demoCase}-study-${v}`)?.study_date??''));}catch(e){setError(translate((e as Error).message));}finally{setBusy(false);}};
 useEffect(()=>{if(viewerReady&&demoCase&&demoCases.some(p=>p.id===demoCase)&&opened.current!==demoCase){opened.current=demoCase;void demo();}},[viewerReady,demoCase]);
 const showDifference=async()=>{setBusy(true);try{const nv=viewers.current[1];let image:NVImage;if(differenceShown)image=await NVImage.loadFromFile({file:masks[1]!.safe,colormap:'red',opacity:.7});else{const a=masks[0]!,b=masks[1]!;assertSameGrid(a.geometry,b.geometry);const d=maskDifference(Uint8Array.from(a.data),Uint8Array.from(b.data));image=await NVImage.loadFromFile({file:maskFile(b.bytes,d.labels),opacity:.7});image.setColormapLabel({R:[0,140,235,45],G:[0,145,142,128],B:[0,155,38,219],A:[0,130,255,255],I:[0,1,2,3],labels:['Háttér','Közös','Csak kontroll','Csak kiinduló']});}while(nv.volumes.length>1)nv.removeVolumeByIndex(1);nv.addVolume(image);setDifferenceShown(!differenceShown);}catch(e){setError(translate((e as Error).message));}finally{setBusy(false);}};
 let sameGrid=false;try{if(sources[0]&&sources[1]){assertSameGrid(sources[0].geometry,sources[1].geometry);sameGrid=true;}}catch{/* independent viewing remains available */}
 const volumes=masks.map(m=>m?measureLabels(m.data,m.geometry).reduce((sum,x)=>sum+x.millilitres,0):null);
 const change=volumes[0]!==null&&volumes[1]!==null&&volumes[0]>0?(volumes[1]-volumes[0])/volumes[0]*100:null;
 const exportReport=()=>downloadText('paired-scan-comparison.json',JSON.stringify({schema:'leletiv.paired-scans.v1',diagnosticUse:false,anatomicalCorrespondenceConfirmed:confirmed,automaticRegistration:false,dates,sources:sources.map(s=>s?{file:s.name,sha256:s.hash,geometry:s.geometry}:null),masks:masks.map(s=>s?{file:s.name,sha256:s.hash}:null),volumesMl:volumes,changePercent:change},null,2),'application/json');
 return <><div className="care-actions" style={{marginBottom:18}}><Link className="button primary" to="/advanced?module=longitudinal">Automatikus illesztés és RECIST-munkalap ↗</Link></div><PageHeader title="Két időpont összehasonlítása" description="Egymás melletti metszetek, szinkronizált tájékozódás és a kijelölt régiók térfogatváltozása." actions={<Link className="button secondary" to="/volume-lab">Vissza a 3D munkatérhez</Link>}/><p className="care-source">A képek illesztése nem automatikus. Az egyező képméret és felbontás önmagában nem bizonyít anatómiai egyezést. A különbségtérképhez előzetesen térben illesztett felvételek és egymásnak megfelelő területkijelölések szükségesek.</p>
 <div className="care-actions" style={{marginBottom:24}}><button className="button secondary" disabled={busy} onClick={()=>void demo()}>Szintetikus összehasonlítás megnyitása</button><small>Geometriai próbaképek, ismert méretű régiókkal. Nem betegadat.</small></div><div className="compare-grid">{[0,1].map(i=><section className="care-panel" key={i}><h2>{i?'Kontrollvizsgálat':'Kiinduló vizsgálat'}</h2><div className="care-form"><label>Vizsgálat dátuma<input type="date" value={dates[i]} onChange={e=>setDates(p=>p.map((v,j)=>i===j?e.target.value:v))}/></label><label className="button primary file-button">Forráskép megnyitása<input type="file" accept=".nii,.nii.gz" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f,i,false);e.target.value='';}}/></label><label className="button secondary file-button">Területkijelölés megnyitása<input type="file" accept=".nii,.nii.gz" disabled={busy||!sources[i]} onChange={e=>{const f=e.target.files?.[0];if(f)void load(f,i,true);e.target.value='';}}/></label></div><p>{sources[i]?.name||'Nincs megnyitott képanyag'}</p><div className="compare-canvas"><canvas ref={i?right:left} aria-label={i?'Kontrollvizsgálat metszetei':'Kiinduló vizsgálat metszetei'}/></div>{i===1&&differenceShown&&<p>Változástérkép: szürke = közös · narancs = csak kontroll · kék = csak kiinduló.</p>}<p>{masks[i]?.name||'Nincs kijelölt terület'}{volumes[i]!==null&&<strong> · {volumes[i]!.toLocaleString('hu-HU',{minimumFractionDigits:3,maximumFractionDigits:3})} ml</strong>}</p></section>)}</div>
 <section className="care-panel comparison-controls"><h2>Összehasonlítás és változástérkép</h2><div className="comparison-checks"><label className="stack-check"><input type="checkbox" checked={confirmed} disabled={busy||!sources.every(Boolean)} onChange={e=>{setConfirmed(e.target.checked);if(!e.target.checked){setSync(false);viewers.current.forEach(nv=>nv.broadcastTo([]));}}}/>Ellenőriztem, hogy ugyanannak a bemutatóesetnek megfelelő régióit és előzetesen térben illesztett vizsgálatait nyitottam meg.</label><label className="stack-check"><input type="checkbox" checked={sync} disabled={busy||!sameGrid||!confirmed} onChange={e=>{setSync(e.target.checked);const a=viewers.current;for(let i=0;i<2;i++)a[i].broadcastTo(e.target.checked?[a[1-i]]:[],{'2d':true,'3d':true});}}/>Metszetek összekapcsolása (egyező képméret, felbontás és ellenőrzött illesztés)</label></div>
 {confirmed&&masks.every(Boolean)&&<p className="comparison-result">A kijelölt terület térfogatváltozása: {change===null?'Nulla kiinduló térfogatból százalék nem számítható.':`${change>0?'+':''}${change.toLocaleString('hu-HU',{minimumFractionDigits:1,maximumFractionDigits:1})}%`} <small>A kijelölt területek össztérfogatának különbsége; nem RECIST-besorolás és nem automatikus terápiás válaszértékelés.</small></p>}
 <div className="care-actions comparison-actions"><button className="button secondary" disabled={busy||!sameGrid||!confirmed||!masks.every(Boolean)} onClick={()=>void showDifference()}>{differenceShown?'Kontrollkijelölés visszaállítása':'Változástérkép megjelenítése'}</button> <button className="button secondary" disabled={busy||!sameGrid||!confirmed||!masks.every(Boolean)} onClick={async()=>{setBusy(true);setError('');try{const a=masks[0]!,b=masks[1]!;assertSameGrid(a.geometry,b.geometry);const diff=maskDifference(Uint8Array.from(a.data,v=>v>0?1:0),Uint8Array.from(b.data,v=>v>0?1:0));const f=maskFile(b.bytes,diff.labels,'change-map.nii');const url=URL.createObjectURL(f),link=document.createElement('a');link.href=url;link.download=f.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setError(`Változástérkép letöltve. 1 = közös (${diff.overlap} képpont), 2 = csak kontroll (${diff.added}), 3 = csak kiinduló (${diff.removed}).`);}catch(e){setError(translate((e as Error).message));}finally{setBusy(false);}}}>Változástérkép letöltése (.nii)</button> <button className="button primary" disabled={!confirmed||!masks.every(Boolean)} onClick={exportReport}>Összehasonlítás exportálása (JSON)</button></div>{error&&<p role="status">{error}</p>}{busy&&<p role="status">Képanyag feldolgozása…</p>}</section></>;
}
