import {medicalLabel} from '../lib/medical-language';
import {useState} from 'react';
import {advanced,artifactUrl,workflows,type Job} from '../lib/advanced';

export function AdvancedSourcePicker({image,onPick}:{image:boolean;onPick:(file:File,source:{jobId:string;artifact:string;reviewVersion:number})=>void}){
 const [open,setOpen]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setOpen(!open);if(!open){try{setJobs((await advanced<Job[]>('/jobs')).filter(j=>j.status==='completed'));}catch(e){setError((e as Error).message);}}};
 return <div className="advanced-source-picker"><button type="button" className="text-button" onClick={()=>void load()}>Korábbi eredmény használata {open?'−':'+'}</button>{open&&<div><label>Korábbi feldolgozás<select value={job?.id??''} onChange={async e=>{setError('');try{setJob(e.target.value?await advanced<Job>(`/jobs/${e.target.value}`):null);}catch(e){setError((e as Error).message);}}}><option value="">Válassz mentett feldolgozást</option>{jobs.map(j=><option key={j.id} value={j.id}>{workflows.find(w=>w.id===j.kind)?.title} · {new Date(j.created*1000).toLocaleString('hu-HU')} · {j.version?'ellenőrzött':'nem ellenőrzött'}</option>)}</select></label>{job&&<label>Átveendő eredmény<select value="" disabled={busy} onChange={async e=>{const name=e.target.value;if(!name)return;setBusy(true);setError('');try{const response=await fetch(artifactUrl(job,name));if(!response.ok)throw new Error('Az eredmény nem olvasható.');onPick(new File([await response.blob()],name),{jobId:job.id,artifact:name,reviewVersion:job.version});setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><option value="">{busy?'Eredmény átvétele…':'Válassz képet vagy területkijelölést'}</option>{job.report!.artifacts.filter(a=>a.kind===(image?'image':'volume')).map(a=><option key={a.file} value={a.file}>{medicalLabel(a.label)}</option>)}</select></label>}<small>A bemenet típusát, képfelbontását, térbeli illeszkedését és klinikai megfelelőségét az átvétel után is ellenőrizni kell.</small></div>}{error&&<small role="alert">{error}</small>}</div>;
}
