import {useSearchParams} from 'react-router-dom';
import {useState} from 'react';
import {AdvancedSourcePicker} from './AdvancedSourcePicker';
import {advanced,type Workflow,workflows} from '../lib/advanced';
import {useAppData} from '../lib/workspace';

export function AdvancedInputs({kind,busy,onStart,onDemo}:{kind:Workflow;busy:boolean;onStart:(form:FormData)=>void;onDemo:()=>void}){
 const [contextParams]=useSearchParams();
 const [preview,setPreview]=useState<{width:number;height:number;image:string;micronsPerPixel:number|null}|null>(null),[previewBusy,setPreviewBusy]=useState(false);
 const [linkedSources,setLinkedSources]=useState<Record<string,{jobId:string;artifact:string;reviewVersion:number}>>({});
 const {data}=useAppData();const [files,setFiles]=useState<Record<string,File>>({}),[options,setOptions]=useState<Record<string,string|number|boolean>>({caseId:contextParams.get('case')||'',petUnits:'SUVbw',tracer:'FDG',suvThreshold:2.5,minimumMl:.1,micronsPerPixel:.5,roiX:0,roiY:0,roiWidth:1024,roiHeight:1024,nucleusThreshold:.035,dabThreshold:.08,minNucleusArea:12,maxNucleusArea:200,adcScale:1,echoTimeMs:30,timeStepSec:1.5,registerSequences:true,baselineFrames:5,bolusStart:5,bolusEnd:15,heightCm:170}),[visits,setVisits]=useState(1),[mriMode,setMriMode]=useState('maps'),[error,setError]=useState('');
 const set=(key:string,value:string|number|boolean)=>setOptions(p=>({...p,[key]:value}));
 const file=(key:string,label:string,required=false)=> <div key={key} className="advanced-file"><label><span>{label}{required?' *':''}</span><input type="file" required={required&&!files[key]} accept={key==='slide'?'.png,.jpg,.jpeg,.tif,.tiff,.svs,.ndpi':key.includes('mask')||['organs','tissue','roi'].includes(key)?'.nii,.nii.gz':'.nii,.nii.gz,.zip'} onChange={e=>{const f=e.target.files?.[0];setLinkedSources(p=>{const n={...p};delete n[key];return n;});setFiles(p=>{const n={...p};if(f)n[key]=f;else delete n[key];return n;});if(key==='slide')setPreview(null);if(key==='slide'&&f&&/\.(png|jpe?g)$/i.test(f.name)){const url=URL.createObjectURL(f),img=new Image();img.onload=()=>{setOptions(p=>({...p,roiX:0,roiY:0,roiWidth:Math.min(img.width,4096),roiHeight:Math.min(img.height,4096)}));URL.revokeObjectURL(url);};img.onerror=()=>URL.revokeObjectURL(url);img.src=url;}}}/><small>{files[key]?`${(files[key].size/1024/1024).toFixed(1)} MB`:'Válassz fájlt a gépedről'}</small></label><AdvancedSourcePicker image={key==='slide'} onPick={(f,source)=>{setFiles(p=>({...p,[key]:f}));setLinkedSources(p=>({...p,[key]:source}));if(key==='slide'){setPreview(null);const url=URL.createObjectURL(f),img=new Image();img.onload=()=>{setOptions(p=>({...p,roiX:0,roiY:0,roiWidth:Math.min(img.width,4096),roiHeight:Math.min(img.height,4096)}));URL.revokeObjectURL(url);};img.onerror=()=>URL.revokeObjectURL(url);img.src=url;}}}/>{files[key]&&<small>{files[key].name}</small>}</div>;
 const num=(key:string,label:string,min:number,max:number,step=1)=><label key={key}>{label}<input type="number" min={min} max={max} step={step} value={String(options[key]??'')} required onChange={e=>set(key,e.target.value===''?'':Number(e.target.value))}/></label>;
 const check=(key:string,label:string,required=true)=><label className="advanced-check" key={key}><input type="checkbox" checked={options[key]===true} required={required} onChange={e=>set(key,e.target.checked)}/><span>{label}</span></label>;
 const selected=workflows.find(w=>w.id===kind)!;
 return <form className="advanced-inputs care-panel" onSubmit={e=>{e.preventDefault();setError('');try{const form=new FormData();const opts:Record<string,unknown>={...options,linkedSources};if(kind==='mri'&&mriMode==='raw'){opts.bValues=String(options.bValues??'').split(/[,;\s]+/).filter(Boolean).map(Number);}for(const [key,value] of Object.entries(files)){if(kind==='longitudinal'&&key.startsWith('followup')&&Number(key.match(/\d+/)?.[0])>visits)continue;if(kind==='mri'&&(mriMode==='raw'?['adc','perfusion']:['dwi','dsc']).includes(key))continue;form.append(key,value);}form.set('options',JSON.stringify(opts));onStart(form);}catch{setError('Ellenőrizd a bemeneteket.');}}}>
 <div className="advanced-section-title"><div><span className="advanced-step">01 · Bemenetek</span><h2>{selected.title}</h2></div><button type="button" className="button secondary" disabled={busy} onClick={onDemo}>Kipróbálás mintával</button></div><p>{selected.input}</p>
 <div className="advanced-fields"><label>Esethez kapcsolás<select value={String(options.caseId??'')} onChange={e=>set('caseId',e.target.value)}><option value="">Önálló kutatási vizsgálat</option>{data?.cases.map(c=><option key={c.id} value={c.id}>{c.hospital_id} · {c.patient_name}</option>)}</select></label><label>Vizsgálat megnevezése<input maxLength={100} placeholder="Például: mellkasi kontroll" value={String(options.title??'')} onChange={e=>set('title',e.target.value)}/></label><label>Vizsgálat dátuma<input type="date" value={String(options.date??'')} onChange={e=>set('date',e.target.value)}/></label></div>
 {kind==='longitudinal'&&<><div className="advanced-fields">{file('baseline','Kiinduló CT / MR',true)}{file('baseline_mask','Kiinduló elváltozások kijelölése',true)}<label>Kontrollok száma<select value={visits} onChange={e=>setVisits(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} kontroll</option>)}</select></label></div>{Array.from({length:visits},(_,i)=><div className="advanced-visit advanced-fields" key={i}>{file(`followup${i+1}`,`${i+1}. kontroll CT / MR`,true)}{file(`followup${i+1}_mask`,`${i+1}. kontroll területkijelölése`,true)}<label>Kontroll dátuma<input type="date" value={String(options[`date${i+1}`]??'')} onChange={e=>set(`date${i+1}`,e.target.value)}/></label></div>)}<p className="advanced-hint">Minden elváltozás külön, 1-től kezdődő egész azonosítót kapjon. Kijelölést a 3D munkatérben is készíthetsz. Az illesztés eltolással és forgatással történik, a szövetek alakváltozását nem korrigálja. Jelentős anatómiai változásnál a párosítást különösen gondosan ellenőrizd.</p></>}
 {kind==='body'&&<><div className="advanced-fields">{file('ct','CT-képanyag',true)}{num('heightCm','Testmagasság (cm)',80,250,.1)}</div><details><summary>Meglévő területkijelölések használata</summary><div className="advanced-fields">{file('organs','Szervkijelölések (TotalSegmentator total)')}{file('tissue','Izom- és zsírszövet kijelölése')}</div><p>Területazonosítók: 1 = teljes vázizomzat, 2 = visceralis zsír, 3 = subcutan zsír, 4 = intermuscularis zsír. A CT-vel azonos képméret, felbontás és térbeli helyzet szükséges.</p></details>{check('huConfirmed','Ellenőriztem, hogy a CT-intenzitások Hounsfield-egységben (HU) vannak.')}</>}
 {kind==='pet'&&<><div className="advanced-fields">{file('ct','CT-képanyag',true)}{file('pet','Kalibrált PET-képanyag',true)}<label>PET-egység<select value={String(options.petUnits)} onChange={e=>set('petUnits',e.target.value)}><option value="SUVbw">SUVbw · testtömegre normalizált</option><option value="BQML">Bq/ml · kalibrált aktivitás</option></select></label><label>Radiofarmakon<select value={String(options.tracer)} onChange={e=>set('tracer',e.target.value)}><option value="FDG">¹⁸F-FDG</option><option value="other">Más radiofarmakon (TLG nélkül)</option></select></label>{num('suvThreshold','Aktivitási küszöb (SUVbw)',.1,100,.1)}{num('minimumMl','Legkisebb régió (ml)',.01,1000,.01)}</div>{options.petUnits==='BQML'&&<div className="advanced-fields">{num('weightKg','Testtömeg (kg)',1,400,.1)}{num('injectedMbq','Nettó beadott aktivitás (MBq)',.01,5000,.01)}{num('halfLifeMin','Felezési idő (perc)',.1,100000,.01)}{num('elapsedMin','Beadástól a felvételig (perc)',0,10000,.1)}<label>Bomláskorrekció<select required value={String(options.decayReference??'')} onChange={e=>set('decayReference',e.target.value)}><option value="">Válassz</option><option value="scan-start">Vizsgálat kezdetére korrigálva</option></select></label></div>}<details><summary>Saját aktivitásrégiók</summary>{file('mask','Területkijelölés az eredeti PET-felvételhez')}</details>{check('alignmentConfirmed','A CT és PET ugyanahhoz a vizsgálathoz tartozik, közös fizikai koordinátarendszerrel.')}</>}
 {kind==='pathology'&&<><div className="advanced-fields">{file('slide','Szövettani kép / metszet',true)}{num('micronsPerPixel','Felbontás (µm/képpont)',.05,20,.01)}{num('roiX','Régió bal széle (képpont)',0,200000)}{num('roiY','Régió felső széle (képpont)',0,200000)}{num('roiWidth','Régió szélessége (képpont)',32,4096)}{num('roiHeight','Régió magassága (képpont)',32,4096)}</div><details><summary>Festés és sejtmag-felismerés beállításai</summary><div className="advanced-fields">{num('nucleusThreshold','Sejtmagküszöb (optikai sűrűség)',.005,2,.005)}{num('dabThreshold','DAB-pozitivitás küszöbe',.005,2,.005)}{num('minNucleusArea','Legkisebb sejtmag (µm²)',1,500)}{num('maxNucleusArea','Legnagyobb sejtmag (µm²)',1,2000)}</div></details><div className="advanced-actions"><button type="button" className="button secondary" disabled={previewBusy||!files.slide||options.researchConfirmed!==true} onClick={async()=>{setPreviewBusy(true);setError('');try{const form=new FormData();form.append('slide',files.slide);form.append('researchConfirmed','true');const result=await advanced<NonNullable<typeof preview>>('/slide-preview',{method:'POST',body:form});setPreview(result);if(result.micronsPerPixel)set('micronsPerPixel',result.micronsPerPixel);}catch(e){setError((e as Error).message);}finally{setPreviewBusy(false);}}}>{previewBusy?'Előnézet készítése…':'Metszet előnézete és régió kijelölése'}</button><small>Előbb erősítsd meg lent a szintetikus használatot.</small></div>{preview&&<><p>{preview.width} × {preview.height} képpont. Kattints a vizsgálandó régió közepére; a méretet a fenti mezőkben állíthatod.</p><div className="advanced-slide" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();setOptions(p=>({...p,roiX:Math.round(Math.max(0,Math.min(preview.width-Number(p.roiWidth),(e.clientX-rect.left)/rect.width*preview.width-Number(p.roiWidth)/2))),roiY:Math.round(Math.max(0,Math.min(preview.height-Number(p.roiHeight),(e.clientY-rect.top)/rect.height*preview.height-Number(p.roiHeight)/2)))}));}}><img src={preview.image} alt="Teljes metszet áttekintő képe a vizsgálati régió kijelöléséhez"/><span className="advanced-roi-box" style={{left:`${Number(options.roiX)/preview.width*100}%`,top:`${Number(options.roiY)/preview.height*100}%`,width:`${Number(options.roiWidth)/preview.width*100}%`,height:`${Number(options.roiHeight)/preview.height*100}%`}}/></div></>}{check('tumorRoiConfirmed','A kijelölt, hematoxilin–DAB festésű tumorrégiót és a µm/képpont értéket szakértő ellenőrizte.')}<p className="advanced-hint">A felismerés sejtmagokat keres; a tumorsejt-besorolás nem automatikus. A nem megfelelő sejteket az eredménynél kizárhatod.</p></>}
 {kind==='mri'&&<><div className="advanced-fields">{file('reference','Anatómiai MR',true)}{file('roi','Vizsgált területek kijelölése')}<label>Bemenet típusa<select value={mriMode} onChange={e=>setMriMode(e.target.value)}><option value="maps">Kész ADC / perfúziós térképek</option><option value="raw">4D DWI / DSC sorozatok</option></select></label></div>{mriMode==='maps'?<div className="advanced-fields">{file('adc','ADC-térkép')}{file('perfusion','Perfúziós térkép')}{num('adcScale','ADC szorzó → mm²/s',.000000001,1,.000001)}</div>:<><div className="advanced-fields">{file('dwi','4D DWI (NIfTI)')}{file('dsc','4D DSC (NIfTI)')}<label>b-értékek (s/mm²), képkockák sorrendjében<input placeholder="0, 500, 1000" value={String(options.bValues??'')} onChange={e=>set('bValues',e.target.value)}/></label>{num('echoTimeMs','DSC TE (ms)',1,200,.1)}{num('timeStepSec','DSC időlépés (s)',.01,30,.01)}{num('baselineFrames','Kontrasztanyag érkezése előtti képek száma',2,1000)}{num('bolusStart','Kontrasztanyag érkezésének képszáma (az első kép: 0)',2,1000)}{num('bolusEnd','Első áthaladás végének képszáma (az első kép: 0)',3,10000)}</div>{check('motionCorrected','A DWI és DSC képkockáinak mozgáskorrekciója megtörtént.')}{check('registerSequences','DWI és DSC automatikus merev illesztése az anatómiai referenciához.',false)}</>}<div className="advanced-fields">{file('normal_mask','Normál referenciaszövet kijelölése az rCBV-hez')}</div>{check('alignmentConfirmed','A bemenetek fizikai illesztését ellenőriztem; a kész térképek térben illeszkednek az anatómiai felvételhez.')}<p className="advanced-hint">Legalább egy diffúziós vagy perfúziós bemenet szükséges. A DSC-becslés nem tartalmaz szivárgáskorrekciót, és nem számít agyi véráramlást (CBF) vagy átlagos áthaladási időt (MTT).</p></>}
 <div className="advanced-submit">{check('researchConfirmed','Kizárólag szintetikus kutatási bemenetet használok. Az eredményt ellenőrizni fogom.')}<p>Helyi feldolgozás · egy fájl legfeljebb 128 MB, együtt 260 MB. A forrás és az eredmény a gépen marad, újraindítás után is megnyitható.</p><button className="button primary" disabled={busy} type="submit">{busy?'Kérés folyamatban…':'Automatikus feldolgozás indítása'}</button>{error&&<p role="alert">{error}</p>}</div>
 </form>;
}
