import {anatomyLabel,medicalLabel,qualityValue} from '../lib/medical-language';
import {useState,type ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {advanced,artifactUrl,number,type Job,type Pair,type Target,type RecistInput} from '../lib/advanced';
import {downloadText} from '../lib/download';

const organOptions=[['lung','Tüdő'],['liver','Máj'],['lymph-nodes','Nyirokcsomók'],['kidney','Vese'],['adrenal','Mellékvese'],['soft-tissue','Lágyrész'],['other','Egyéb szerv']];
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="advanced-table-scroll"><table className="advanced-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export function AdvancedReview({job,onSaved,onFocus}:{job:Job;onSaved:(job:Job)=>void;onFocus:(p:number[])=>void}){
 const report=job.report!,saved=job.review;
 const [reviewer,setReviewer]=useState(saved?.reviewer??''),[note,setNote]=useState(saved?.note??''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [matches,setMatches]=useState<Pair[][]>(saved?.matching??report.visits?.map(v=>v.matching)??[]),[recist,setRecist]=useState(!!saved?.recistInputs),[targets,setTargets]=useState<Target[]>(saved?.recistInputs?.targets??[]),[nonTarget,setNonTarget]=useState(saved?.recistInputs?.nonTarget??report.visits?.map(()=>'not-assessed')??[]),[newLesions,setNewLesions]=useState(saved?.recistInputs?.newLesions??report.visits?.map(()=>'uncertain')??[]);
 const [included,setIncluded]=useState<number[]>(saved?.includedRegions??[]),[cells,setCells]=useState<Record<string,string>>(saved?.cells??{}),[cellPage,setCellPage]=useState(0),[cellImage,setCellImage]=useState('cells.png'),[selectedCell,setSelectedCell]=useState<number|null>(null),[history,setHistory]=useState<{version:number;created:number;payload:{reviewer:string;note:string}}[]|null>(null);
 const patchTarget=(i:number,patch:Partial<Target>)=>setTargets(p=>p.map((v,j)=>i===j?{...v,...patch}:v));
 const addTarget=(id:number)=>{const region=report.baseline!.find(r=>r.label===id)!;if(targets.some(t=>t.id===id)||targets.length>=5)return;setTargets(p=>[...p,{id,organ:'',lymphNode:false,baselineMm:Math.round(region.maxInPlaneDiameterMm*10)/10,followupMm:report.visits!.map((v,i)=>{const match=matches[i]?.find(m=>m.baselineLabel===id);const r=v.regions.find(r=>r.label===match?.followupLabel);return r?Math.round(r.maxInPlaneDiameterMm*10)/10:null;})}]);};
 const save=async()=>{setBusy(true);setError('');setNotice('');try{const input:RecistInput={targets,nonTarget,newLesions};const updated=await advanced<Job>(`/jobs/${job.id}/review`,{method:'POST',body:JSON.stringify({version:job.version,reviewer,note,confirmed,matching:matches,recist:recist?input:null,includedRegions:included,cells})});onSaved(updated);setConfirmed(false);setHistory(null);setNotice('Az ellenőrzés mentve. Az eredmény újranyitás után is elérhető.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const cellCounts=(report.cells??[]).reduce((s,c)=>{const state=cells[c.id]??(c.positive?'positive':'negative');s[state]=(s[state]??0)+1;return s;},{} as Record<string,number>);
 const viable=(cellCounts.positive??0)+(cellCounts.negative??0);
 const petRows=report.regions?.filter(r=>included.includes(r.label))??[];
 const compositionNames:Record<string,string>={sliceIndex:'L3 metszet száma (az első: 0)',selectedMuscleAreaCm2:'Kijelölt izomterület (cm²)',selectedMuscleMeanHu:'Kijelölt izom átlagos HU',fatRangeAreaCm2:'Zsírtartomány teljes területe (cm²)',totalMuscleAreaCm2:'Teljes izomterület (cm²)',skeletalMuscleIndexCm2M2:'Vázizomindex (cm²/m²)',visceralFatAreaCm2:'Visceralis zsírterület (cm²)',subcutaneousFatAreaCm2:'Subcutan zsírterület (cm²)',intermuscularFatAreaCm2:'Intermuscularis zsírterület (cm²)',muscleMeanHu:'Teljes izom átlagos HU'};
 return <><section className="advanced-results care-panel"><div className="advanced-section-title"><div><span className="advanced-step">03 · Mérések és javítás</span><h2>{job.kind==='pathology'?'Sejtek ellenőrzése':'Mérési eredmények'}</h2></div><span className="advanced-pill">{saved?`${job.version}. ellenőrzés mentve`:'Még nem ellenőrzött'}</span></div>
 {job.kind==='longitudinal'&&<><p>Az automatikus párosítás módosítható. A „nem azonosítható” választás nem jelenti az elváltozás eltűnését.</p>{report.visits!.map((v,vi)=><div className="advanced-visit" key={v.index}><h3>{vi+1}. kontroll {v.date&&`· ${v.date}`}</h3><p>Közös látómező: {number(v.registration.coverageFraction*100,1)}%. Ez geometriai adat, nem az illesztési pontosság mértéke.</p><Table headers={['Kiinduló régió','Kiinduló ml','Kontroll megfeleltetése','Kontroll ml','Változás']}>
 {report.baseline!.map(r=>{const m=matches[vi]?.find(m=>m.baselineLabel===r.label);const follow=v.regions.find(x=>x.label===m?.followupLabel);return <tr key={r.label}><td><button className="text-button" onClick={()=>onFocus(r.centerRasMm)}>Régió {r.label} ↗</button></td><td>{number(r.volumeMl,3)}</td><td><select aria-label={`${vi+1}. kontroll, ${r.label}. régió párosítása`} value={m?.followupLabel??''} onChange={e=>{const value=e.target.value?Number(e.target.value):null;setMatches(p=>p.map((list,i)=>i===vi?list.map(x=>x.baselineLabel===r.label?{...x,followupLabel:value}:x):list));setConfirmed(false);}}><option value="">Nem azonosítható</option>{v.regions.map(x=><option key={x.label} value={x.label}>Régió {x.label}</option>)}</select></td><td>{number(follow?.volumeMl,3)}</td><td>{follow&&r.volumeMl>0?`${number((follow.volumeMl/r.volumeMl-1)*100,1)}%`:'—'}</td></tr>;})}</Table><p>Párosítás nélkül maradt kontrollrégiók: {v.regions.filter(r=>!matches[vi]?.some(m=>m.followupLabel===r.label)).map(r=>r.label).join(', ')||'nincs'}.</p></div>)}
 <label className="advanced-check"><input type="checkbox" checked={recist} onChange={e=>setRecist(e.target.checked)}/>RECIST 1.1 munkalap kitöltése</label>{recist&&<div className="advanced-recist"><h3>Ellenőrzött átmérők</h3><p>A kijelölésből számított átmérő csak kezdőérték. A mérési síkot és a mm-értékeket ellenőrizd; nyirokcsomónál a rövid tengelyt add meg. A RECIST nem agyi gliómára kidolgozott RANO-értékelés.</p><label>Célelváltozás hozzáadása (legfeljebb 5)<select value="" disabled={targets.length>=5} onChange={e=>addTarget(Number(e.target.value))}><option value="">Válassz régiót</option>{report.baseline!.filter(r=>!targets.some(t=>t.id===r.label)).map(r=><option key={r.label} value={r.label}>Régió {r.label}</option>)}</select></label>{targets.map((t,i)=><fieldset key={t.id}><legend>Célelváltozás · {t.id}. régió</legend><div className="advanced-fields"><label>Szerv<select value={t.organ} onChange={e=>patchTarget(i,{organ:e.target.value,lymphNode:e.target.value==='lymph-nodes'})}><option value="">Válassz szervet</option>{organOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Kiinduló átmérő (mm)<input type="number" min={0} max={1000} step=".1" value={t.baselineMm} onChange={e=>patchTarget(i,{baselineMm:Number(e.target.value)})}/></label>{t.followupMm.map((mm,j)=><label key={j}>{j+1}. kontroll (mm)<input type="number" min={0} max={1000} step=".1" value={mm??''} onChange={e=>patchTarget(i,{followupMm:t.followupMm.map((v,k)=>k===j?(e.target.value===''?null:Number(e.target.value)):v)})}/></label>)}</div><button className="text-button" onClick={()=>setTargets(p=>p.filter((_,j)=>j!==i))}>Célelváltozás eltávolítása</button></fieldset>)}{report.visits!.map((_,i)=><div className="advanced-fields" key={i}><label>{i+1}. kontroll · nem célelváltozások<select value={nonTarget[i]} onChange={e=>setNonTarget(p=>p.map((v,j)=>j===i?e.target.value:v))}><option value="not-assessed">Nem értékelhető / nem értékelt</option><option value="absent">Nincsenek / eltűntek, a szükséges feltételek teljesülnek</option><option value="present">Fennállnak, egyértelmű progresszió nélkül</option><option value="progression">Egyértelmű progresszió</option></select></label><label>Új elváltozás<select value={newLesions[i]} onChange={e=>setNewLesions(p=>p.map((v,j)=>j===i?e.target.value:v))}><option value="uncertain">Bizonytalan / nem értékelt</option><option value="no">Nincs</option><option value="yes">Egyértelműen igazolt új elváltozás</option></select></label></div>)}<p>A munkalap kategóriái a képi ellenőrzés mentésekor számítódnak ki. A nem mérhető, túl kicsi vagy bizonytalan elváltozás értékét ne helyettesítsd önkényesen nullával.</p></div>}
 {saved?.recist&&<><h3>Mentett RECIST-munkalap</h3><Table headers={['Kontroll','Átmérőösszeg','Kiindulóhoz','Korábbi legkisebb átmérőösszeg','Összesített kategória']}>{saved.recist.visits.map(v=><tr key={v.visit}><td>{v.visit}.</td><td>{number(v.sumMm)} mm</td><td>{number(v.baselineChangePercent)}%</td><td>{number(v.nadirBeforeMm)} mm</td><td><strong>{v.overallResponse}</strong></td></tr>)}</Table><p>{saved.recist.limitations}</p></>}
 </>}
 {job.kind==='body'&&<><h3>Testösszetétel · L3</h3>{report.composition?<><div className="advanced-metrics">{Object.entries(report.composition).filter(([k])=>compositionNames[k]).map(([k,v])=><div key={k}><span>{compositionNames[k]}</span><strong>{typeof v==='number'?number(v):v??'—'}</strong></div>)}</div><p>{medicalLabel(String(report.composition.method))}</p></>:<p>Az L3 csigolya nem található a kijelölt területek között. L3-alapú testösszetételi mérés nem készült.</p>}<h3>Anatómiai régiók</h3><Table headers={['Régió','Térfogat','Képi hely']} >{report.regions!.map(r=><tr key={r.label}><td>{anatomyLabel(r.name)}</td><td>{number(r.volumeMl,1)} ml</td><td><button className="text-button" onClick={()=>onFocus(r.centerRasMm)}>Megmutatás ↗</button></td></tr>)}</Table></>}
 {job.kind==='pet'&&<><p>Csak a képen ellenőrzött, megfelelő régiókat jelöld be. Az automatikus jelöltek között élettani halmozás is lehet.</p><div className="advanced-metrics"><div><span>Kiválasztott régiók</span><strong>{included.length}</strong></div><div><span>Kiválasztott térfogat</span><strong>{number(petRows.reduce((s,r)=>s+r.volumeMl,0))} ml</strong></div>{report.tracer==='FDG'&&<div><span>TLG · kiválasztott régiók</span><strong>{number(petRows.reduce((s,r)=>s+(r.tlg??0),0))}</strong></div>}</div><Table headers={['Beszámít','Régió','Térfogat','SUVmean','SUVmax','TLG']}>{report.regions!.map(r=><tr key={r.label}><td><input type="checkbox" aria-label={`${r.label}. aktivitásrégió beszámítása`} checked={included.includes(r.label)} onChange={e=>{setIncluded(p=>e.target.checked?[...p,r.label]:p.filter(x=>x!==r.label));setConfirmed(false);}}/></td><td><button className="text-button" onClick={()=>onFocus(r.centerRasMm)}>Régió {r.label} ↗</button></td><td>{number(r.volumeMl)} ml</td><td>{number(r.suvMean)}</td><td>{number(r.suvMax)}</td><td>{number(r.tlg)}</td></tr>)}</Table>{!report.regions!.length&&<p>A megadott küszöb mellett nincs aktivitásrégió. Ez nem negatív diagnosztikai lelet.</p>}</>}
 {job.kind==='pathology'&&<><div className="advanced-metrics"><div><span>Beszámított sejtmag</span><strong>{viable}</strong></div><div><span>DAB-pozitív</span><strong>{cellCounts.positive??0}</strong></div><div><span>Pozitív sejtmagarány</span><strong>{viable?number((cellCounts.positive??0)/viable*100,1)+'%':'—'}</strong></div><div><span>Kizárt</span><strong>{cellCounts.excluded??0}</strong></div></div><div className="advanced-controls"><label>Kép<select value={cellImage} onChange={e=>setCellImage(e.target.value)}><option value="cells.png">Automatikus sejtmagjelölések</option><option value="slide.png">Eredeti vizsgált régió</option></select></label></div><div className="advanced-slide" onClick={e=>{if(!report.cells?.length)return;const rect=e.currentTarget.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*report.roi!.width+report.roi!.x,y=(e.clientY-rect.top)/rect.height*report.roi!.height+report.roi!.y;const nearest=report.cells.reduce((a,b)=>Math.hypot(a.x-x,a.y-y)<Math.hypot(b.x-x,b.y-y)?a:b);setSelectedCell(nearest.id);setCellPage(Math.floor((nearest.id-1)/30));}}><img src={artifactUrl(job,cellImage)} alt="Kijelölt hematoxilin–DAB régió; kattints egy sejtmagra a kiválasztásához"/>{selectedCell&&(()=>{const c=report.cells!.find(c=>c.id===selectedCell)!;return <span className="advanced-cell-focus" style={{left:`${(c.x-report.roi!.x)/report.roi!.width*100}%`,top:`${(c.y-report.roi!.y)/report.roi!.height*100}%`}}/>;})()}</div><p>Piros: automatikusan pozitív, kék: automatikusan negatív. A képen kattintva kiválasztható a legközelebbi sejtmag; a javításokat az alábbi táblázat és a mentett összesítés tartalmazza.</p><Table headers={['Sejtmag','Terület','DAB-sűrűség','Ellenőrzött besorolás']}>{report.cells!.slice(cellPage*30,cellPage*30+30).map(c=><tr className={selectedCell===c.id?'is-selected':''} key={c.id}><td><button className="text-button" onClick={()=>setSelectedCell(c.id)}>#{c.id}</button></td><td>{number(c.areaUm2)} µm²</td><td>{number(c.dabOpticalDensity,3)}</td><td><select aria-label={`${c.id}. sejtmag besorolása`} value={cells[c.id]??(c.positive?'positive':'negative')} onChange={e=>{setCells(p=>({...p,[c.id]:e.target.value}));setConfirmed(false);}}><option value="positive">Pozitív</option><option value="negative">Negatív</option><option value="excluded">Kizárt / nem tumorsejt</option></select></td></tr>)}</Table><div className="advanced-actions"><button className="button secondary" disabled={cellPage===0} onClick={()=>setCellPage(p=>p-1)}>Előző 30</button><span>{cellPage+1}. / {Math.max(1,Math.ceil(report.cells!.length/30))}. oldal</span><button className="button secondary" disabled={(cellPage+1)*30>=report.cells!.length} onClick={()=>setCellPage(p=>p+1)}>Következő 30</button></div></>}
 {job.kind==='mri'&&<><h3>Régióstatisztika</h3><Table headers={['Térkép','Régió','Méréshez használt képpontok','Medián','10. percentilis','90. percentilis']}>{report.measurements!.map((m,i)=><tr key={i}><td>{m.map}</td><td>{m.region}</td><td>{m.validVoxels}</td><td>{number(m.median,6)}</td><td>{number(m.p10,6)}</td><td>{number(m.p90,6)}</td></tr>)}</Table>{!report.measurements!.length&&<p>A térképek elkészültek. Régiónkénti méréshez tölts fel az anatómiai felvételhez térben illeszkedő területkijelölést.</p>}<p>ADC: mm²/s. rCBV: a kijelölt normál referenciaszövethez viszonyított, dimenzió nélküli arány. A DSC-integrál egysége a számítás szerint ΔR2* × idő; nem abszolút CBV.</p><details><summary>Számítási módszer és minőségi adatok</summary>{Object.entries(report.quality??{}).map(([k,v])=><p key={k}>{medicalLabel(k)}: {qualityValue(k,v)}</p>)}</details></>}
 <aside className="advanced-limitations"><strong>Az eredmény értelmezése</strong><ul>{report.limitations.map(t=><li key={t}>{medicalLabel(t)}</li>)}</ul></aside></section>
 <section className="care-panel advanced-signoff"><span className="advanced-step">04 · Ellenőrzés és dokumentálás</span><h2>Ellenőrzés rögzítése</h2><div className="advanced-fields"><label>Ellenőrző neve<input value={reviewer} maxLength={120} onChange={e=>setReviewer(e.target.value)} placeholder="Név / kutatói azonosító"/></label><label>Megjegyzés<textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} placeholder="Képi megfelelés, javítások, korlátok"/></label></div><label className="advanced-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Ellenőriztem a képeket, a régiókat és a fenti méréseket. A mentés nem jelent klinikai validálást.</label><div className="advanced-actions"><button className="button primary" disabled={busy||!confirmed||!reviewer.trim()} onClick={()=>void save()}>Ellenőrzés mentése</button><button className="button secondary" disabled={busy} onClick={()=>{void advanced<typeof history>(`/jobs/${job.id}/history`).then(setHistory).catch(e=>setError(e.message));}}>Korábbi ellenőrzések</button></div>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}{history&&<div>{history.length?history.map(h=><p key={h.version}><strong>{h.version}. változat · {h.payload.reviewer}</strong> · {new Date(h.created*1000).toLocaleString('hu-HU')}<br/>{h.payload.note||'Nincs megjegyzés.'}</p>):<p>Még nincs mentett ellenőrzés.</p>}</div>}</section>
 <section className="care-panel advanced-export"><h2>Eredménycsomag</h2><p>{saved?`Mentett ellenőrzés: ${saved.reviewer} · ${new Date(saved.time*1000).toLocaleString('hu-HU')}`:'Az eredmény még nem ellenőrzött.'} A PDF a mentett eredményt tartalmazza; a még nem mentett javítások nem kerülnek bele.</p><div className="advanced-actions"><Link className="button primary" to={`/advanced/report/${job.id}`}>PDF-jelentés megnyitása</Link><button className="button secondary" onClick={async()=>{try{const revisions=await advanced<unknown>(`/jobs/${job.id}/history`);downloadText(`leletiv-${job.kind}-${job.id}.json`,JSON.stringify({job,revisions},null,2),'application/json');}catch(e){setError((e as Error).message);}}}>Teljes eredmény (JSON)</button>{report.artifacts.map(a=><a className="button secondary" key={a.file} href={artifactUrl(job,a.file)} download={a.file}>{medicalLabel(a.label)} ↓</a>)}</div></section></>;
}
