import {translate,recordText} from '../lib/i18n';
import {medicalLabel} from '../lib/medical-language';
import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useAppData} from '../lib/workspace';
import {apiRequest} from '../lib/api';
import {readNifti} from '../shared/volume';
import {hashBytes} from '../shared/nifti-data';
import type {ScanAnalysis} from '../shared/care';
export function ArchiveBridge({source,disabled,hasMask,getMask,onOpen,method,parameters}:{source:File|null;disabled:boolean;hasMask:boolean;getMask:()=>File|null;onOpen:(source:File,mask?:File,analysis?:ScanAnalysis)=>Promise<void>;method:string;parameters:Record<string,unknown>}){
 const {data,reload}=useAppData();const [params]=useSearchParams();const [studyId,setStudyId]=useState(params.get('study')||'');const [caseId,setCaseId]=useState('');const [rows,setRows]=useState<ScanAnalysis[]>([]);const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const attempted=useRef('');
 useEffect(()=>{const id=params.get('study');if(id){setStudyId(id);attempted.current='';}},[params.get('study')]);
 const [modality,setModality]=useState('MR');
 const study=data?.studies.find(s=>s.id===studyId);const locked=busy||disabled;
 const list=async(id=studyId)=>setRows(await apiRequest<ScanAnalysis[]>(`/api/scans/studies/${id}/analyses`));
 useEffect(()=>{let active=true;setRows([]);if(studyId)void apiRequest<ScanAnalysis[]>(`/api/scans/studies/${studyId}/analyses`).then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[studyId]);
 async function open(analysis?:ScanAnalysis){if(!study?.object_key)return;setBusy(true);setMessage('');try{const r=await fetch(`/api/studies/${study.id}/download`);if(!r.ok)throw new Error('A forráskép nem tölthető be.');const file=new File([await r.blob()],study.file_name||'scan.nii');let mask:File|undefined;if(analysis){const safe=await readNifti(file);if(await hashBytes(await safe.arrayBuffer())!==analysis.source_hash)throw new Error('A mentett eredmény másik forrásképhez tartozik.');const m=await fetch(`/api/scans/analyses/${analysis.id}/mask`);if(!m.ok)throw new Error('A területkijelölés nem tölthető be.');mask=new File([await m.blob()],'saved-region.nii');}await onOpen(file,mask,analysis);setMessage('Az archív képanyag megnyílt.');}catch(e){setMessage(e instanceof Error?e.message:'A megnyitás nem sikerült.');}finally{setBusy(false);}}
 useEffect(()=>{const key=params.get('study');if(!key||disabled||busy||!study||study.id!==key||attempted.current===key)return;const analysis=params.get('analysis');if(analysis&&!rows.some(r=>r.id===analysis))return;attempted.current=key;void open(rows.find(r=>r.id===analysis));},[disabled,study,rows]);
 return <section id="archive-bridge" className="care-panel archive-bridge"><h2>Archívum és mérési napló</h2><p>Nyisd meg az esethez tartozó NIfTI-felvételt; a területkijelölést és a méréseket a pontos forrásképhez kötve mentheted.</p><fieldset disabled={locked} className="care-form">
 <label>Archív térfogati felvétel<select value={studyId} onChange={e=>setStudyId(e.target.value)}><option value="">Válassz vizsgálatot</option>{data?.studies.filter(s=>s.object_key&&/\.nii(\.gz)?$/i.test(s.file_name||'')).map(s=><option key={s.id} value={s.id}>{s.patient_name} · {recordText(s.description)}</option>)}</select></label><button className="button secondary" disabled={!study?.object_key} onClick={()=>void open()}>Képanyag megnyitása</button>
 {source&&<details><summary>A most megnyitott helyi felvétel archiválása</summary><label>Eset<select value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Válassz esetet</option>{data?.cases.map(c=><option key={c.id} value={c.id}>{c.patient_name} · {c.hospital_id}</option>)}</select></label><label>Modalitás<select value={modality} onChange={e=>setModality(e.target.value)}><option value="MR">MR</option><option value="CT">CT</option></select></label><button className="button secondary" disabled={!caseId} onClick={async()=>{setBusy(true);setMessage('');try{const f=new FormData();f.set('file',source);f.set('case_id',caseId);f.set('description',source.name);f.set('modality',modality);const r=await apiRequest<{id:string}>('/api/studies/upload',{method:'POST',body:f});await reload();setStudyId(r.id);setMessage('A forráskép az archívumba került.');}catch(e){setMessage(translate((e as Error).message));}finally{setBusy(false);}}}>Forráskép mentése az esethez</button><small>Legfeljebb 25 MB; a képanyag és a kiválasztott modalitás az esethez kerül.</small></details>}
 </fieldset>
 <form className="care-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),mask=getMask();if(!source||!mask)return;setBusy(true);setMessage('');try{f.set('mask',mask);f.set('source_hash',await hashBytes(await(await readNifti(source)).arrayBuffer()));f.set('method',method);f.set('parameters',JSON.stringify({...parameters,sourceFile:source.name,diagnosticUse:false}));await apiRequest(`/api/scans/studies/${studyId}/analyses`,{method:'POST',body:f});await list();setMessage('Kijelölés és mérések elmentve. Az eredmény ellenőrzésre vár.');}catch(e){setMessage(translate((e as Error).message));}finally{setBusy(false);}}}>
 <fieldset disabled={locked||!source||!studyId||!hasMask} className="care-form"><label>Állandó régióazonosító<input name="region_id" placeholder="pl. góc-01" required maxLength={100}/></label><label>Megjegyzés / vizsgálati körülmények<textarea name="note" required maxLength={1000}/></label><button className="button primary">Kijelölés és mérések mentése az esethez</button></fieldset></form>
 {message&&<p role="status">{message}</p>}{rows.map(r=><article className="care-row" key={r.id}><h3>{r.region_id}</h3><p>{medicalLabel(r.method)} · {r.review_status==='reviewed'?'Áttekintve':'Ellenőrzésre vár'} · {r.created_at.slice(0,10)}</p><p>{r.note}</p><p>{JSON.parse(r.measurements_json).map((m:{label:number;millilitres:number})=>`${m.label}: ${m.millilitres.toLocaleString('hu-HU',{minimumFractionDigits:3,maximumFractionDigits:3})} ml`).join(' · ')||'Nincs kijelölt terület'}</p><button className="button secondary" disabled={locked} onClick={()=>void open(r)}>Felvétel és kijelölés visszanyitása</button>{r.review_status==='unreviewed'&&<form className="care-form" onSubmit={async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await apiRequest(`/api/scans/analyses/${r.id}/review`,{method:'POST',body:JSON.stringify(b)});await list();}catch(e){setMessage(translate((e as Error).message));}finally{setBusy(false);}}}><label>Áttekintő személy<select name="actor_id" required disabled={locked}><option value="">Válassz személyt</option>{data?.team.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="button secondary" disabled={locked}>Áttekintés rögzítése</button></form>}</article>)}{study&&<Link to={`/care?case=${study.case_id}`}>Az eset teljes képértékelési naplója →</Link>}</section>;
}
