import {medicalLabel} from '../lib/medical-language';
import {useEffect,useState} from 'react';
import {localize as l} from '../lib/i18n';
import {downloadText} from '../lib/download';
const service='http://127.0.0.1:8789';
type Candidate={id:number;score:number;centerRasMm:number[];boxRasMm:number[][]};
type Report={candidates:Candidate[];elapsedSeconds:number;[key:string]:unknown};
type Job={id:string;kind:string;profile:string;status:string;stage:string;progress:number;error:string|null;report:Report|null};
async function request<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(service+path,{...init,headers:{'X-Leletiv-Research':'1',...init?.headers},signal:AbortSignal.timeout(30000)});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b&&typeof b==='object'&&'detail' in b&&typeof b.detail==='string'?b.detail:'A helyi képfeldolgozó nem érhető el.');}return r.json();}
export function LungAssistant({disabled,active,onResult,onLocate}:{disabled:boolean;active:boolean;onResult:(source:File,boxes:File)=>Promise<void>;onLocate:(point:number[])=>void}){
 const [file,setFile]=useState<File|null>(null),[confirmed,setConfirmed]=useState(false),[ready,setReady]=useState(false),[job,setJob]=useState<Job|null>(null),[sending,setSending]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[reviews,setReviews]=useState<Record<number,string>>({});
 const busy=sending||job?.status==='queued'||job?.status==='running';
 const check=async()=>{try{const h=await request<{lungWeightsInstalled:boolean}>('/health');setReady(h.lungWeightsInstalled);const jobs=await request<Job[]>('/jobs');setJob(jobs.find(j=>j.kind==='lung')??null);setError('');}catch{setReady(false);setError('A helyi modell nem fut. Indítás: npm run dev:full');}};
 useEffect(()=>{void check();},[]);
 useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;let active=true;const id=setInterval(()=>{void request<Job>(`/jobs/${job.id}`).then(j=>{if(active){setJob(j);setError('');}}).catch(()=>{if(active)setError('Megszakadt a kapcsolat. A feldolgozás a helyi szolgáltatásban folytatódhat.');});},1500);return()=>{active=false;clearInterval(id);};},[job?.id,job?.status]);
 const start=async(demo=false)=>{setSending(true);setLoaded(false);setError('');setReviews({});try{const b=new FormData();if(file)b.set('ct',file);b.set('prepared','yes');setJob(await request<Job>(demo?'/lung/smoke':'/lung/jobs',{method:'POST',body:demo?undefined:b}));}catch(e){setError((e as Error).message);}finally{setSending(false);}};
 const show=async()=>{if(!job)return;setSending(true);setError('');try{const files=await Promise.all(['source','mask'].map(async part=>{const r=await fetch(`${service}/jobs/${job.id}/${part}`,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error('Az eredmény nem tölthető be.');return new File([await r.blob()],part==='source'?'CT-source.nii.gz':'candidate-boxes.nii.gz');}));await onResult(files[0],files[1]);setLoaded(true);}catch(e){setError((e as Error).message);}finally{setSending(false);}};
 return <section id="lung-assistant" className="care-panel lung-assistant"><div className="section-heading"><div><span className="section-kicker">Helyi képi mesterséges intelligencia</span><h2>Tüdőgócjelöltek CT-felvételen</h2></div><button className="button secondary" disabled={busy} onClick={()=>void check()}>Kapcsolat ellenőrzése</button></div><p>A MONAI RetinaNet előtanított modellje térbeli jelölteket keres, amelyeket egyenként megnyithatsz és megjegyzéssel láthatsz el. A számítás ezen a számítógépen fut.</p><div className="care-source">Kutatási prototípus. A jelölődoboz nem az elváltozás pontos körvonala, a modellpontszám nem a rosszindulatúság valószínűsége. Téves és kihagyott jelöltek is lehetségesek; az üres eredmény nem zár ki betegséget.</div>
 <fieldset className="care-form" disabled={busy}><label>Kalibrált mellkasi CT (.nii / .nii.gz)<input type="file" accept=".nii,.nii.gz" onChange={e=>{setFile(e.target.files?.[0]??null);setConfirmed(false);}}/></label><small>Hounsfield-skála, milliméterben megadott térbeli felbontás és ismert képtájolás szükséges. JPG/PNG-sorozat nem használható ehhez a modellhez. Helyi CPU-korlát: 12 millió térbeli képpont, 64 MB fájl.</small><label className="stack-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Ellenőriztem: szintetikus vagy személyazonosításra nem alkalmas kutatási mellkasi CT-t választottam, megfelelő HU-kalibrációval.</label><div className="care-actions"><button className="button primary" disabled={!ready||!confirmed||!file} onClick={()=>void start()}>Tüdőgócjelöltek keresése</button><button className="button secondary" disabled={!ready} onClick={()=>void start(true)}>Szintetikus modellpróba</button></div></fieldset>
 {job&&<div className="lung-result"><p role="status"><strong>{l(job.stage)}</strong> · {job.progress}% {job.profile==='synthetic-smoke'&&'· szintetikus teszt'}</p><progress value={job.progress} max={100}/>{job.error&&<p role="alert">{medicalLabel(job.error)}</p>}{busy&&<button className="text-button" disabled={sending} onClick={async()=>{try{await request(`/jobs/${job.id}`,{method:'DELETE'});setError('Megszakítás kérve; az aktuális modellművelet befejezése után áll le.');}catch(e){setError((e as Error).message);}}}>Feldolgozás megszakítása</button>}{!['queued','running'].includes(job.status)&&<button className="text-button" disabled={sending} onClick={async()=>{setSending(true);try{await request(`/jobs/${job.id}`,{method:'DELETE'});setJob(null);setLoaded(false);setReviews({});}catch(e){setError((e as Error).message);}finally{setSending(false);}}}>Ideiglenes futás törlése</button>}{job.report&&<><div className="care-actions"><button className="button primary" disabled={disabled||sending} onClick={()=>void show()}>Jelöltek megnyitása a 3D munkatérben</button><button className="button secondary" onClick={()=>downloadText('lung-candidate-review.json',JSON.stringify({...job.report,localReviewNotes:reviews,reviewNotesAreDiagnosticConclusions:false},null,2),'application/json')}>Jelöltlista és megjegyzések exportálása</button></div><p>{job.report.candidates.length} megjelenített jelölt · {job.report.elapsedSeconds.toLocaleString('hu-HU')} másodperc. A megjegyzések az exportban őrizhetők meg.</p>{job.report.candidates.map(c=><article className="care-row" key={c.id}><div className="care-actions"><h3>{c.id}. jelölt</h3><span>Modellpontszám: {new Intl.NumberFormat('hu-HU',{maximumFractionDigits:4}).format(c.score)}</span><button className="button secondary" disabled={!loaded||disabled||!active} onClick={()=>onLocate(c.centerRasMm)}>Ugrás a jelölthöz</button></div><label>Áttekintési megjegyzés<textarea maxLength={1000} value={reviews[c.id]??''} onChange={e=>setReviews(p=>({...p,[c.id]:e.target.value}))}/></label></article>)}</>}</div>}{error&&<p role="status">{medicalLabel(l(error))}</p>}</section>;
}
